### ISSUE TITLE
Minimap is not working

### ISSUE THREAD

**Issue by ajainvivek** [antvis/Graphin#205]
**Describe the bug**

Minimap component isn't working with the recent version 2.0.0-beta.9. 

Throws error `graph.getWidth is not a function`

**To Reproduce**

https://codesandbox.io/s/zen-chaum-2i9im

**Expected behavior**

Minimap component to render without error

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: chrome
 - Version 87.0

**Comment by pomelo-nwu** [comment]
@ajainvivek Yes, the packaging problem. graphin-components@2.0.0-beta.7 depends on graphin@2.0.0-beta5. Therefore, in the project, graphin@beta.9 version and beta5 version of GraphinContext are different objects, so there is no automatic perception of react context Variety. Just upgrade graphin-components to beta.9 version. In the follow-up, we adopt an automated packaging solution to reduce the occurrence of such problems.

**Comment by ajainvivek** [comment]
Thanks, @pomelo-nwu. Upgrade to version graphin-components to beta.9 version does works. Thanks for the quick and prompt response.
